Rewrite the heimdal-strength tests in Perl
Externalize the passwords and expected results in a JSON file
and rewrite the test case in Perl, making it read the list of
test cases from that file.  Add a stripped-down krb5.conf file
used by the test suite instead of trying to manipulate the system
krb5.conf file.

diff --git a/tests/heimdal/external-t b/tests/heimdal/external-t
--- a/tests/heimdal/external-t
+++ b/tests/heimdal/external-t
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/perl
 #
 # Test suite for basic Heimdal external strength checking functionality.
 #
@@ -8,106 +8,153 @@
 #
 # See LICENSE for licensing terms.
 
-. "$SOURCE/tap/libtap.sh"
-cd "$BUILD/data"
+use 5.006;
+use strict;
+use warnings;
 
-# Run heimdal-strength to check a password.  Takes the test description,
-# the principal, the password, the expected exit status, the expected output
-# to standard output, and the expected output to standard error.
-ok_password () {
-    desc="$1"
-    princ="$2"
-    password="$3"
-    w_status="$4"
-    w_stdout="$5"
-    w_stderr="$6"
-    rm -f input
-    echo "principal: $princ" > input
-    echo "new-password: $password" >> input
-    echo 'end' >> input
-    stdout=`"$BUILD/../external/heimdal-strength" "$princ" < input 2> errors`
-    status="$?"
-    echo "# status: $status"
-    echo "# stdout: $stdout"
-    ok "$desc: status" [ "$status" -eq "$w_status" ]
-    ok "$desc: stdout" [ "$stdout" = "$w_stdout" ]
-    stderr=`cat errors`
-    echo "# stderr: $stderr"
-    ok "$desc: stderr" [ "$stderr" = "$w_stderr" ]
-    rm -f input errors
+use lib "$ENV{SOURCE}/tap/perl";
+
+use File::Copy qw(copy);
+use Test::RRA qw(use_prereq);
+use Test::RRA::Automake qw(test_file_path);
+
+use_prereq('File::Slurp');
+use_prereq('IPC::Run', 'run');
+use_prereq('JSON');
+use_prereq('Test::More', '0.87_01');
+
+# Run the newly-built heimdal-strength command to check a password and reports
+# the results using Test::More.  This uses the standard protocol for Heimdal
+# external password strength checking programs.
+#
+# $test_ref - Reference to hash of test parameters
+#   name      - The name of the test case
+#   principal - The principal changing its password
+#   password  - The new password
+#   status    - If present, the exit status (otherwise, it should be 0)
+#   error     - If present, the expected rejection error
+#
+# Returns: undef
+#  Throws: Text exception on failure to run the test program
+sub check_password {
+    my ($test_ref) = @_;
+
+    # Build the input to the strength checking program.
+    my $in = "principal: $test_ref->{principal}\n";
+    $in .= "new-password: $test_ref->{password}\n";
+    $in .= "end\n";
+
+    # Find the newly-built password checking program.
+    my $program = test_file_path('../external/heimdal-strength');
+
+    # Run the password strength checker.
+    my $out;
+    my $err;
+    run([$program, $test_ref->{principal}], \$in, \$out, \$err);
+    my $status = ($? >> 8);
+    chomp($out, $err);
+
+    # Check the results.  If there is an error in the password, it should come
+    # on standard error; otherwise, standard output should be APPROVED.  If
+    # there is a non-zero exit status, we expect the error on standard error
+    # and use that field to check for system errors.
+    is($status, $test_ref->{status} || 0, "$test_ref->{name} (status)");
+    if (defined($test_ref->{error})) {
+        is($err, $test_ref->{error}, '...error message');
+        is($out, q{}, '...no output');
+    } else {
+        is($err, q{},        '...no errors');
+        is($out, "APPROVED", '...approved');
+    }
+    return;
 }
 
-# We need a modified krb5.conf file to add the password_dictionary setting.
-# We first generate a modified copy of the krb5.conf file that doesn't contain
-# this setting so that we can test error handling.
-krb5conf=
-for p in /etc/krb5.conf /usr/local/etc/krb5.conf data/krb5.conf ; do
-    if [ -r "$p" ] ; then
-        krb5conf="$p"
-        sed -e '/^[ 	]*password_dictionary[ 	]*=/d' "$p" > ./krb5.conf
-        KRB5_CONFIG="./krb5.conf"
-        export KRB5_CONFIG
-        break
-    fi
-done
-if [ -z "$krb5conf" ] ; then
-    skip_all 'no krb5.conf found, put one in tests/data/krb5.conf'
-fi
+# Create a new krb5.conf file that includes password dictionary configuration
+# so that subsequent invocations of heimdal-strength can find the testing
+# dictionary.
+#
+# Returns: Path to the new krb5.conf file
+#  Throws: Text exception if the new krb5.conf file cannot be created
+sub create_krb5_conf {
+    my $old    = test_file_path('data/krb5.conf');
+    my $tmpdir = $ENV{BUILD} ? "$ENV{BUILD}/tmp" : 'tests/tmp';
+    my $new    = "$tmpdir/krb5.conf";
 
-# Okay, we should be good to run the test suite.
-plan `expr 18 \* 3`
+    # Create a temporary directory for the new file.
+    if (!-d $tmpdir) {
+        mkdir($tmpdir, 0777) or die "Cannot create $tmpdir: $!\n";
+    }
 
-# We don't have a password_dictionary setting, so we should fail with an
-# initialization error.
-ok_password "no dictionary configured" 'test@EXAMPLE.ORG' 'password' 1 '' \
-    'password_dictionary not configured in krb5.conf'
+    # Start with the testing krb5.conf file shipped in the package.
+    copy($old, $new) or die "Cannot copy $old to $new: $!\n";
 
-# Now add the password dictionary configuration.
-cat <<EOF >> ./krb5.conf
+    # Append the local configuration.
+    my $datadir = $ENV{BUILD} ? "$ENV{BUILD}/data" : 'tests/data';
+    open(my $config, '>>', $new) or die "Cannot append to $new: $!\n";
+    print {$config} <<"__END__"
 
 [appdefaults]
     krb5-strength = {
-        password_dictionary = $BUILD/data/dictionary
+        password_dictionary = $datadir/dictionary
     }
+__END__
+      or die "Cannot append to $new: $!\n";
+    close($config) or die "Cannot append to $new: $!\n";
 
-EOF
+    # Return the path to the new file.
+    return $new;
+}
 
-# Check the basic functionality.
-ok_password 'good password' 'test@EXAMPLE.ORG' 'known good password' 0 \
-    'APPROVED' ''
-ok_password 'password in dictionary' 'test@EXAMPLE.ORG' 'password' 0 '' \
-    'it is based on a dictionary word'
-ok_password 'password in dictionary' 'test@EXAMPLE.ORG' 'bitterbane' 0 '' \
-    'it is based on a dictionary word'
-ok_password 'password in dictionary repeated' 'test@EXAMPLE.ORG' \
-    'stanfordstanford' 0 '' 'it is based on a (duplicated) dictionary word'
-ok_password 'password in dictionary' 'test@EXAMPLE.ORG' 'enabrettib' 0 '' \
-    'it is based on a (reversed) dictionary word'
-ok_password 'password seven characters' 'test@EXAMPLE.ORG' 'dfareas' 0 '' \
-    'it is too short'
-ok_password 'password too short' 'test@EXAMPLE.ORG' 'food' 0 '' \
-    'it is too short'
-ok_password 'password way too short' 'test@EXAMPLE.ORG' 'foo' 0 '' \
-    "it's WAY too short"
-ok_password 'password empty' 'test@EXAMPLE.ORG' '' 0 '' \
-    "it's WAY too short"
-ok_password 'password all whitespace' 'test@EXAMPLE.ORG' '  	      ' 0 '' \
-    'it does not contain enough DIFFERENT characters'
-ok_password 'password too simplistic' 'test@EXAMPLE.ORG' 'abcdefghi' 0 '' \
-    'it is too simplistic/systematic'
-ok_password 'not enough characters' 'test@EXAMPLE.ORG' '22413411' 0 '' \
-    'it does not contain enough DIFFERENT characters'
-ok_password 'password based on principal' 'someuser@EXAMPLE.ORG' 'someuser' \
-    0 '' 'Password based on username'
-ok_password 'password based on principal' 'someuser@EXAMPLE.ORG' 'resuemos' \
-    0 '' 'Password based on username'
-ok_password 'password is username with digits' 'someuser@EXAMPLE.ORG' \
-    'someuser123' 0 '' 'Password based on username'
-ok_password 'password is principal' 'test@EXAMPLE.ORG' 'test@EXAMPLE.ORG' \
-    0 '' 'Password based on username'
-ok_password 'long password complexity test' 'test@EXAMPLE.ORG' \
-    "OwenDericksegregationistshumiliatemeningitis'smainmast" 0 \
-    'APPROVED' ''
+# Load a password test cases and return them as a list.
+#
+# $file - The path to the file containing the test data in JSON
+#
+# Returns: List of anonymous hashes representing password test cases
+#  Throws: Text exception on failure to load the test data
+sub load_password_tests {
+    my ($file) = @_;
 
-# Clean up.
-rm -f krb5.conf
+    # Load the test file data into memory.
+    my $testdata = read_file($file);
+
+    # Decode the JSON into Perl objects and return them.
+    my $json = JSON->new->utf8;
+    return $json->decode($testdata);
+}
+
+# Find our initial test krb5.conf file.
+local $ENV{KRB5_CONFIG} = test_file_path('data/krb5.conf');
+
+# Run a test with no Kerberos password dictionary configuration and check that
+# we get the correct error message.
+my $test = {
+    name      => 'no dictionary configured',
+    principal => 'test@EXAMPLE.COM',
+    password  => 'password',
+    status    => 1,
+    error     => 'password_dictionary not configured in krb5.conf',
+};
+check_password($test);
+
+# Install the krb5.conf file with a configuration pointing to the test
+# dictionary.
+local $ENV{KRB5_CONFIG} = create_krb5_conf();
+
+# Load and run the password tests from JSON.
+my $tests = load_password_tests(test_file_path('data/cracklib.json'));
+for my $test (@{$tests}) {
+    check_password($test);
+}
+
+# Tell Test::More that we've finished running all of our test cases.
+done_testing();
+
+# Clean up our temporary krb5.conf file on any exit.
+END {
+    my $tmpdir = $ENV{BUILD} ? "$ENV{BUILD}/tmp" : 'tests/tmp';
+    my $config = "$tmpdir/krb5.conf";
+    if (-f $config) {
+        unlink($config) or warn "Cannot remove $config\n";
+        rmdir($tmpdir);
+    }
+}
